// src/pages/AboutMe.jsx
import { motion } from "framer-motion";
import gearData from "../data/GearData.json";

const focusAreas = [
  {
    title: "Infrastructure",
    items: ["Docker", "Kubernetes", "CI/CD", "Linux"],
    color: "bg-[#79c8ff]",
  },
  {
    title: "Development",
    items: ["Golang", "Python", "PHP", "Automation"],
    color: "bg-[#ffd166]",
  },
  {
    title: "Security",
    items: ["CTF", "Digital Forensics", "Bug Hunting", "Hardening"],
    color: "bg-[#ff8fab]",
  },
];

const principles = [
  "Memecah masalah rumit menjadi langkah yang jelas dan bisa dikerjakan.",
  "Mendokumentasikan keputusan agar tim tidak bergantung pada satu orang.",
  "Menyeimbangkan kecepatan eksperimen dengan keamanan dan kemudahan perawatan.",
];

export default function AboutMe() {
  return (
    <motion.div
      key="about"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      transition={{ duration: 0.25 }}
      className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20"
    >
      <header className="grid gap-8 lg:grid-cols-[0.75fr_1.25fr] lg:items-end">
        <div>
          <p className="pixel-font mb-4 text-[10px] text-[#6c5ce7]">ABOUT PLAYER 01</p>
          <h1 className="text-4xl font-black tracking-tight sm:text-5xl">Orang di balik layar.</h1>
        </div>
        <p className="max-w-3xl text-lg leading-relaxed text-[#4b5368] sm:text-xl">
          Saya Aliezzar, pembelajar aktif yang menikmati pertemuan antara cloud, keamanan, software, dan AI. Saya suka membangun hal praktis, mengotomatiskan pekerjaan berulang, lalu menjelaskan hasilnya dengan bahasa yang mudah dimengerti.
        </p>
      </header>

      <div className="my-12 pixel-divider" />

      <section className="grid gap-8 lg:grid-cols-[1.2fr_0.8fr]" aria-labelledby="story-title">
        <article className="pixel-panel p-6 sm:p-9">
          <div className="mb-7 flex items-center gap-3">
            <span className="grid h-10 w-10 place-items-center border-2 border-[#17213c] bg-[#75d6ad] font-black">A</span>
            <h2 id="story-title" className="text-2xl font-black">Cerita singkat</h2>
          </div>
          <div className="space-y-5 text-[#4b5368]">
            <p>
              Ketertarikan saya berawal dari rasa penasaran tentang bagaimana sebuah sistem bekerja—dan bagaimana membuatnya lebih baik. Dari sana saya mulai bereksperimen dengan Linux, bahasa pemrograman, infrastruktur, keamanan siber, sampai agentic AI.
            </p>
            <p>
              Saya paling menikmati proyek yang punya dampak nyata: deployment lebih sederhana, proses manual menjadi otomatis, data lebih mudah dipahami, atau pengguna merasa produk lebih nyaman digunakan.
            </p>
            <p>
              Di luar teknis, saya suka menonton VTuber, bermain game, dan mengikuti tantangan Capture the Flag. Semua itu melatih kreativitas, ketelitian, dan cara berpikir dari berbagai sudut.
            </p>
          </div>
        </article>

        <aside className="pixel-panel bg-[#6c5ce7] p-6 text-white sm:p-8" aria-labelledby="currently-title">
          <p className="pixel-font text-[9px] text-[#ffd166]">CURRENT QUEST</p>
          <h2 id="currently-title" className="mt-4 text-2xl font-black" style={{color: 'black'}}>Sedang saya dalami</h2>
          <ul className="mt-7 space-y-4">
            {["Kubernetes & CI/CD", "Golang untuk tooling", "Digital forensics", "Agentic AI workflows"].map((item, index) => (
              <li key={item} className="flex gap-3 border-2 border-white/80 bg-[#4338a8] p-4 font-bold shadow-[3px_3px_0_#ffd166]">
                <span className="text-[#ffd166]">0{index + 1}</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </aside>
      </section>

      <section className="py-16" aria-labelledby="focus-title">
        <div className="mb-9">
          <p className="pixel-font mb-3 text-[10px] text-[#6c5ce7]">TOOLBOX</p>
          <h2 id="focus-title" className="text-3xl font-black">Area yang saya kerjakan</h2>
        </div>
        <div className="grid gap-6 md:grid-cols-3">
          {focusAreas.map((area) => (
            <article key={area.title} className="pixel-panel-sm overflow-hidden">
              <h3 className={`border-b-2 border-[#17213c] p-5 text-xl font-black ${area.color}`}>{area.title}</h3>
              <ul className="grid grid-cols-2 gap-3 p-5">
                {area.items.map((item) => (
                  <li key={item} className="pixel-badge justify-center text-center">{item}</li>
                ))}
              </ul>
            </article>
          ))}
        </div>
      </section>

      <section className="grid gap-8 lg:grid-cols-2" aria-labelledby="principles-title">
        <div className="pixel-panel p-6 sm:p-8">
          <p className="pixel-font text-[9px] text-[#6c5ce7]">HOW I WORK</p>
          <h2 id="principles-title" className="mt-4 text-2xl font-black">Prinsip kerja</h2>
          <ol className="mt-6 space-y-5">
            {principles.map((principle, index) => (
              <li key={principle} className="flex gap-4">
                <span className="pixel-font mt-1 text-[9px] text-[#6c5ce7]">0{index + 1}</span>
                <p className="text-[#4b5368]">{principle}</p>
              </li>
            ))}
          </ol>
        </div>

        <div className="pixel-panel p-6 sm:p-8">
          <p className="pixel-font text-[9px] text-[#6c5ce7]">SETUP</p>
          <h2 className="mt-4 text-2xl font-black">Peralatan sehari-hari</h2>
          <div className="mt-6 grid gap-4 sm:grid-cols-2">
            {gearData.gearType.map((group) => (
              <article key={group.gear} className="border-2 border-[#17213c] bg-[#f3e7cd] p-4">
                <h3 className="font-black">{group.gear}</h3>
                <p className="mt-2 text-sm text-[#5d6475]">{group.gearList.map((item) => item.item).join(" · ")}</p>
              </article>
            ))}
          </div>
        </div>
      </section>
    </motion.div>
  );
}

// src/pages/AboutMe.vue
<template>
  <div class="space-y-8">
    <!-- Header Summary -->
    <header class="rounded-xl border border-slate-200 bg-white p-6 sm:p-8 shadow-sm">
      <p class="font-mono text-xs font-semibold uppercase tracking-wider text-blue-600 mb-2">
        About Me
      </p>
      <h1 class="text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">
        Tentang saya
      </h1>
      <p class="mt-3 max-w-3xl text-sm leading-relaxed text-slate-600 sm:text-base">
        Saya Aliezzar Wijaya, praktisi Cloud, DevOps, dan Keamanan Sistem dari SMK Telkom Sidoarjo (SIJA). Berfokus pada arsitektur yang bersih, otomatisasi deployment, dan ketahanan infrastruktur.
      </p>
    </header>

    <!-- Background & Current Focus Grid -->
    <section class="grid gap-6 sm:grid-cols-2">
      <article class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
        <h2 class="text-base font-bold text-slate-900 mb-3 border-b border-slate-100 pb-2">
          Cerita singkat
        </h2>
        <div class="space-y-3 text-xs leading-relaxed text-slate-600 sm:text-sm">
          <p>
            Ketertarikan saya berawal dari rasa penasaran tentang bagaimana sebuah sistem bekerja, dan bagaimana membuatnya lebih baik. Dari sana saya mulai bereksperimen dengan Linux, bahasa pemrograman, infrastruktur, keamanan siber, sampai agentic AI.
          </p>
          <p>
            Saya paling menikmati proyek yang punya dampak nyata: deployment lebih sederhana, proses manual menjadi otomatis, atau data lebih mudah dipahami.
          </p>
          <p>
            Di luar teknis, saya menyukai tantangan Capture the Flag dan eksperimen tools open source untuk mengasah pemecahan masalah secara terstruktur.
          </p>
        </div>
      </article>

      <aside class="dashed-card p-6 flex flex-col justify-between">
        <div>
          <h2 class="text-base font-bold text-slate-900 mb-3 border-b border-slate-200 pb-2">
            Sedang didalami
          </h2>
          <ul class="space-y-2.5">
            <li
              v-for="(item, index) in currentQuests"
              :key="item"
              class="flex items-center gap-3 text-xs sm:text-sm font-medium text-slate-700"
            >
              <span class="font-mono text-xs text-blue-600 font-bold">0{{ index + 1 }}.</span>
              <span>{{ item }}</span>
            </li>
          </ul>
        </div>

        <div class="mt-6 pt-4 border-t border-slate-200">
          <span class="font-mono text-[11px] text-slate-500">Prinsip: Sederhanakan sebelum optimasi.</span>
        </div>
      </aside>
    </section>

    <!-- Toolbox / Skill Matrix -->
    <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
      <h2 class="text-base font-bold text-slate-900 mb-4 border-b border-slate-100 pb-2">
        Toolbox &amp; Area Kerja
      </h2>
      <div class="grid gap-4 sm:grid-cols-3">
        <div v-for="area in focusAreas" :key="area.title" class="space-y-2">
          <h3 class="font-mono text-xs font-bold uppercase tracking-wider text-slate-500">
            {{ area.title }}
          </h3>
          <div class="flex flex-wrap gap-1.5">
            <span
              v-for="item in area.items"
              :key="item"
              class="clean-badge text-xs"
            >
              {{ item }}
            </span>
          </div>
        </div>
      </div>
    </section>

    <!-- Setup / Gear -->
    <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
      <h2 class="text-base font-bold text-slate-900 mb-4 border-b border-slate-100 pb-2">
        Peralatan &amp; Lingkungan Kerja
      </h2>
      <div class="grid gap-3 sm:grid-cols-2">
        <div
          v-for="group in gearData.gearType"
          :key="group.gear"
          class="rounded-lg border border-slate-100 bg-slate-50/70 p-3.5"
        >
          <p class="font-mono text-xs font-bold text-slate-800">{{ group.gear }}</p>
          <p class="mt-1 text-xs text-slate-600 leading-relaxed">
            {{ group.gearList.map((item) => item.item).join(", ") }}
          </p>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import gearData from "../data/GearData.json";

const focusAreas = [
  {
    title: "Infrastructure",
    items: ["Docker", "Kubernetes", "CI/CD", "Linux", "Nginx"],
  },
  {
    title: "Development",
    items: ["Golang", "Python", "PHP", "Vue.js", "Automation"],
  },
  {
    title: "Security",
    items: ["CTF", "Digital Forensics", "Hardening", "Web Security"],
  },
];

const currentQuests = [
  "Kubernetes & CI/CD Pipelines",
  "Golang untuk tooling & CLI",
  "Digital Forensics & Incident Analysis",
  "Agentic AI autonomous workflows",
];
</script>
