// src/pages/ContactMe.vue
<template>
  <div class="space-y-8">
    <header class="rounded-xl border border-slate-200 bg-white p-6 sm:p-8 shadow-sm">
      <p class="font-mono text-xs font-semibold uppercase tracking-wider text-blue-600 mb-2">
        Direct Contact
      </p>
      <h1 class="text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">
        Kontak &amp; Diskusi
      </h1>
      <p class="mt-3 max-w-xl text-sm leading-relaxed text-slate-600">
        Terbuka untuk diskusi proyek, konsultasi infrastruktur, kolaborasi CTF, atau peluang kerja.
      </p>
    </header>

    <div class="grid gap-6 sm:grid-cols-[0.8fr_1.2fr]">
      <!-- Quick channels -->
      <aside class="space-y-3">
        <div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
          <h2 class="text-xs font-bold uppercase tracking-wider text-slate-500 mb-3 font-mono">
            Kanal Langsung
          </h2>
          <div class="space-y-2">
            <template v-for="linkKey in siteConfig.contactLinkKeys" :key="linkKey">
              <a
                v-if="getSiteLink(linkKey)"
                :href="getSiteLink(linkKey).href"
                target="_blank"
                rel="noreferrer"
                class="flex items-center gap-3 p-2.5 rounded-lg border border-slate-100 bg-slate-50/70 hover:bg-slate-100 hover:border-slate-300 transition-colors"
              >
                <span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-white border border-slate-200 text-slate-700">
                  <DynamicIcon :name="getSiteLink(linkKey).icon" class="text-sm" />
                </span>
                <div class="min-w-0">
                  <p class="text-[11px] font-bold text-slate-500 font-mono">{{ getSiteLink(linkKey).label }}</p>
                  <p class="text-xs font-semibold text-slate-900 truncate">{{ getSiteLink(linkKey).value }}</p>
                </div>
              </a>
            </template>
          </div>
        </div>

        <div class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm text-xs text-slate-600">
          <p>Waktu respons umum: 1-2 hari kerja.</p>
        </div>
      </aside>

      <!-- Message Form -->
      <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
        <h2 class="text-base font-bold text-slate-900 mb-4 border-b border-slate-100 pb-2">
          Kirim Pesan
        </h2>

        <form @submit.prevent="sendEmail" class="space-y-4">
          <div>
            <label for="form_name" class="block text-xs font-semibold text-slate-700 mb-1.5">
              Nama
            </label>
            <input
              id="form_name"
              type="text"
              required
              v-model="formData.form_name"
              placeholder="Nama kamu"
              class="clean-input"
            />
          </div>

          <div>
            <label for="email" class="block text-xs font-semibold text-slate-700 mb-1.5">
              Email
            </label>
            <input
              id="email"
              type="email"
              required
              v-model="formData.email"
              placeholder="email@example.com"
              class="clean-input"
            />
          </div>

          <div>
            <label for="message" class="block text-xs font-semibold text-slate-700 mb-1.5">
              Pesan
            </label>
            <textarea
              id="message"
              rows="4"
              required
              v-model="formData.message"
              placeholder="Ceritakan tentang proyek atau ide yang ingin didiskusikan..."
              class="clean-input resize-y"
            />
          </div>

          <div v-if="status === 'success'" class="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-xs font-semibold text-emerald-800">
            Pesan kamu berhasil dikirim! Saya akan segera merespons.
          </div>

          <div v-if="status === 'error'" class="rounded-lg border border-rose-200 bg-rose-50 p-3 text-xs font-semibold text-rose-800">
            Gagal mengirim pesan. Silakan coba lagi atau kirim via email langsung.
          </div>

          <button
            type="submit"
            :disabled="status === 'loading'"
            class="clean-button clean-button-primary w-full text-xs"
          >
            {{ status === 'loading' ? "Mengirim..." : "Kirim Pesan" }}
          </button>
        </form>
      </section>
    </div>
  </div>
</template>

<script setup>
import { ref } from "vue";
import emailjs from "@emailjs/browser";
import DynamicIcon from "../components/DynamicIcon.vue";
import { getSiteLink, siteConfig } from "../data/SiteConfig";

const status = ref("idle");
const formData = ref({ form_name: "", email: "", message: "" });

const sendEmail = async () => {
  status.value = "loading";

  try {
    await emailjs.send(
      import.meta.env.VITE_EMAIL_SERVICE || process.env.REACT_APP_EMAIL_SERVICE,
      import.meta.env.VITE_EMAIL_TEMPLATE || process.env.REACT_APP_EMAIL_TEMPLATE,
      {
        from_name: formData.value.form_name,
        message: formData.value.message,
        email: formData.value.email,
      },
      import.meta.env.VITE_EMAIL_JS_USER_ID || process.env.REACT_APP_EMAIL_JS_USER_ID
    );
    status.value = "success";
    formData.value = { form_name: "", email: "", message: "" };
  } catch (error) {
    status.value = "error";
  }
};
</script>

// src/pages/ContactMe.jsx
import emailjs from "@emailjs/browser";
import { motion } from "framer-motion";
import { useRef, useState } from "react";
import DynamicIcon from "../components/DynamicIcon";
import { getSiteLink, isExternalLink, siteConfig } from "../data/SiteConfig";

export default function ContactMe() {
  const formRef = useRef(null);
  const [status, setStatus] = useState("idle");
  const [formData, setFormData] = useState({ form_name: "", email: "", message: "" });

  const sendEmail = async (event) => {
    event.preventDefault();
    setStatus("loading");

    try {
      await emailjs.send(
        process.env.REACT_APP_EMAIL_SERVICE,
        process.env.REACT_APP_EMAIL_TEMPLATE,
        {
          from_name: formData.form_name,
          message: formData.message,
          email: formData.email,
        },
        process.env.REACT_APP_EMAIL_JS_USER_ID
      );
      setStatus("success");
      setFormData({ form_name: "", email: "", message: "" });
      formRef.current?.reset();
    } catch {
      setStatus("error");
    }
  };

  return (
    <motion.div
      key="contact"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      transition={{ duration: 0.25 }}
      className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20"
    >
      <header className="max-w-3xl">
        <p className="pixel-font mb-4 text-[10px] text-[#6c5ce7]">START A CONVERSATION</p>
        <h1 className="text-4xl font-black tracking-tight sm:text-5xl">Ada ide, peluang, atau sekadar ingin kenalan?</h1>
        <p className="mt-5 text-lg text-[#4b5368]">
          Ceritakan kebutuhanmu dengan bahasa biasa. Saya akan membalas sejelas dan secepat yang saya bisa.
        </p>
      </header>

      <div className="mt-12 grid gap-10 lg:grid-cols-[0.75fr_1.25fr]">
        <aside className="space-y-5" aria-labelledby="direct-contact-title">
          <div className="pixel-panel bg-[#6c5ce7] p-6 text-white sm:p-8">
            <p className="pixel-font text-[9px] text-[#ffd166]">QUICK CONTACT</p>
            <h2 id="direct-contact-title" className="mt-4 text-2xl font-black">Jalur langsung</h2>
            <p className="mt-3 text-white/85">Pilih platform yang paling nyaman untukmu.</p>
          </div>

          {siteConfig.contactLinkKeys.map((linkKey) => {
            const contact = getSiteLink(linkKey);
            const className = "pixel-panel-sm flex min-h-[76px] items-center gap-4 p-4 transition-transform hover:-translate-y-1";
            const content = (
              <>
                <span className={`grid h-12 w-12 shrink-0 place-items-center border-2 border-[#17213c] ${contact.color}`}>
                  <DynamicIcon name={contact.icon} className="text-2xl" />
                </span>
                <span className="min-w-0">
                  <span className="block text-sm font-bold text-[#5d6475]">{contact.label}</span>
                  <span className="block truncate font-black">{contact.value}</span>
                </span>
              </>
            );

            return isExternalLink(contact.href) ? (
              <a key={linkKey} href={contact.href} target="_blank" rel="noreferrer" className={className}>
                {content}
              </a>
            ) : (
              <a key={linkKey} href={contact.href} className={className}>
                {content}
              </a>
            );
          })}

          <div className="border-2 border-dashed border-[#17213c] bg-[#f3e7cd] p-5">
            <p className="font-bold">Biasanya saya membalas dalam 1–2 hari kerja.</p>
          </div>
        </aside>

        <section className="pixel-panel p-6 sm:p-9" aria-labelledby="contact-form-title">
          <div className="mb-8 flex items-center gap-3">
            <span className="grid h-10 w-10 place-items-center border-2 border-[#17213c] bg-[#ff8fab] font-black">M</span>
            <div>
              <p className="text-sm font-bold text-[#5d6475]">Kirim pesan</p>
              <h2 id="contact-form-title" className="text-2xl font-black">Mari mulai dari sini</h2>
            </div>
          </div>

          <form ref={formRef} onSubmit={sendEmail} className="space-y-6">
            <div className="grid gap-6 sm:grid-cols-2">
              <div>
                <label htmlFor="contact-name" className="mb-2 block font-black">Nama</label>
                <input
                  id="contact-name"
                  name="user_name"
                  type="text"
                  autoComplete="name"
                  required
                  className="pixel-input"
                  placeholder="Nama lengkap"
                  value={formData.form_name}
                  onChange={(event) => setFormData({ ...formData, form_name: event.target.value })}
                />
              </div>
              <div>
                <label htmlFor="contact-email" className="mb-2 block font-black">Email</label>
                <input
                  id="contact-email"
                  name="user_email"
                  type="email"
                  autoComplete="email"
                  required
                  className="pixel-input"
                  placeholder="nama@perusahaan.com"
                  value={formData.email}
                  onChange={(event) => setFormData({ ...formData, email: event.target.value })}
                />
              </div>
            </div>

            <div>
              <label htmlFor="contact-message" className="mb-2 block font-black">Pesan</label>
              <textarea
                id="contact-message"
                name="message"
                rows="7"
                required
                className="pixel-input resize-y"
                placeholder="Halo Aliezzar, saya ingin membahas..."
                value={formData.message}
                onChange={(event) => setFormData({ ...formData, message: event.target.value })}
              />
            </div>

            <div className="flex flex-col gap-4 sm:flex-row sm:items-center">
              <button type="submit" disabled={status === "loading"} className="pixel-button pixel-button-primary disabled:cursor-not-allowed disabled:opacity-60">
                {status === "loading" ? "Mengirim..." : "Kirim pesan"}
                <span aria-hidden="true">→</span>
              </button>
              <div className="min-h-[24px]" aria-live="polite">
                {status === "success" ? <p className="font-bold text-[#176746]">Pesan terkirim. Terima kasih!</p> : null}
                {status === "error" ? <p className="font-bold text-[#b42318]">Pesan belum terkirim. Silakan coba lagi atau gunakan email langsung.</p> : null}
              </div>
            </div>
          </form>
        </section>
      </div>
    </motion.div>
  );
}
