// src/pages/Home.jsx
import { motion } from "framer-motion";
import DynamicCta from "../components/DynamicCta";
import { siteConfig } from "../data/SiteConfig";

const strengths = [
  {
    number: "01",
    title: "Cloud & DevOps",
    description: "Membangun deployment dan infrastruktur yang rapi, otomatis, serta mudah dirawat.",
    color: "bg-[#79c8ff]",
  },
  {
    number: "02",
    title: "Cyber Security",
    description: "Terbiasa melihat sistem dari sisi keamanan, forensik digital, dan kompetisi CTF.",
    color: "bg-[#ff8fab]",
  },
  {
    number: "03",
    title: "Agentic AI",
    description: "Mengeksplorasi AI sebagai rekan kerja untuk otomasi, produk, dan eksperimen kreatif.",
    color: "bg-[#75d6ad]",
  },
];

export default function Home({ onNavigate }) {
  return (
    <motion.div
      key="home"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      transition={{ duration: 0.25 }}
    >
      <section className="relative overflow-hidden border-b-[3px] border-[#17213c]">
        <div className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-16 sm:px-6 sm:py-20 lg:grid-cols-[1.25fr_0.75fr] lg:px-8 lg:py-24">
          <div>
            <div className="mb-6 inline-flex items-center gap-3 border-2 border-[#17213c] bg-[#75d6ad] px-3 py-2 shadow-[3px_3px_0_#17213c]">
              <span className="h-3 w-3 animate-pulse border-2 border-[#17213c] bg-white" />
              <span className="text-sm font-bold">Terbuka untuk kolaborasi dan peluang baru</span>
            </div>

            <p className="pixel-font mb-5 text-[11px] text-[#4338a8] sm:text-xs">HALO, SAYA</p>
            <h1 className="max-w-4xl text-5xl font-black leading-[0.98] tracking-[-0.05em] sm:text-6xl lg:text-7xl">
              Aliezzar
              <span className="block text-[#6c5ce7]">Wijaya.</span>
            </h1>
            <p className="mt-7 max-w-2xl text-lg font-medium leading-relaxed text-[#3d465e] sm:text-xl">
              Saya membangun sistem cloud, otomasi DevOps, dan eksperimen AI yang membantu pekerjaan jadi lebih cepat, aman, dan mudah dipahami.
            </p>

            <div className="mt-9 flex flex-col gap-4 sm:flex-row sm:flex-wrap">
              {siteConfig.homeCtas.map((cta) => (
                <DynamicCta
                  key={`${cta.type}-${cta.target || cta.linkKey}`}
                  cta={cta}
                  onNavigate={onNavigate}
                />
              ))}
            </div>
          </div>

          <div className="relative mx-auto w-full max-w-md" aria-hidden="true">
            <div className="pixel-panel relative aspect-square overflow-hidden bg-[#79c8ff] p-7 sm:p-10">
              <div className="absolute left-6 top-6 h-5 w-5 bg-[#fffaf0] shadow-[20px_0_0_#fffaf0,40px_0_0_#fffaf0,0_20px_0_#fffaf0]" />
              <div className="absolute bottom-0 left-0 h-20 w-full border-t-[3px] border-[#17213c] bg-[#75d6ad]" />
              <div className="pixel-float absolute inset-x-0 top-1/2 mx-auto h-40 w-40 -translate-y-1/2 border-[3px] border-[#17213c] bg-[#ffd166] shadow-[12px_12px_0_#17213c] sm:h-48 sm:w-48">
                <div className="absolute left-8 top-10 h-8 w-8 bg-[#17213c] sm:left-10 sm:top-12" />
                <div className="absolute right-8 top-10 h-8 w-8 bg-[#17213c] sm:right-10 sm:top-12" />
                <div className="absolute bottom-9 left-1/2 h-3 w-16 -translate-x-1/2 bg-[#17213c] sm:bottom-11 sm:w-20" />
                <div className="absolute -left-5 bottom-4 h-16 w-5 border-y-[3px] border-l-[3px] border-[#17213c] bg-[#ff8fab]" />
                <div className="absolute -right-5 bottom-4 h-16 w-5 border-y-[3px] border-r-[3px] border-[#17213c] bg-[#ff8fab]" />
              </div>
              <span className="pixel-font absolute bottom-7 left-1/2 z-10 -translate-x-1/2 whitespace-nowrap text-[9px]">PLAYER 01</span>
            </div>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20" aria-labelledby="strengths-title">
        <div className="mb-10 max-w-2xl">
          <p className="pixel-font mb-3 text-[10px] text-[#6c5ce7]">SKILL SET</p>
          <h2 id="strengths-title" className="text-3xl font-black tracking-tight sm:text-4xl">
            Yang bisa saya bantu kerjakan
          </h2>
          <p className="mt-4 text-lg text-[#5d6475]">
            Penjelasan singkat tanpa jargon berlebihan—supaya tim teknis maupun nonteknis langsung paham nilainya.
          </p>
        </div>

        <div className="grid gap-6 md:grid-cols-3">
          {strengths.map((strength) => (
            <article key={strength.title} className="pixel-panel-sm flex h-full flex-col p-6 sm:p-7">
              <span className={`pixel-font mb-8 grid h-12 w-12 place-items-center border-2 border-[#17213c] text-[10px] ${strength.color}`}>
                {strength.number}
              </span>
              <h3 className="text-xl font-black">{strength.title}</h3>
              <p className="mt-3 text-[#5d6475]">{strength.description}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="border-t-[3px] border-[#17213c] bg-[#ffd166]">
        <div className="mx-auto flex max-w-7xl flex-col gap-6 px-4 py-12 sm:px-6 md:flex-row md:items-center md:justify-between lg:px-8">
          <div>
            <p className="pixel-font text-[10px]">{siteConfig.closingCta.eyebrow}</p>
            <h2 className="mt-3 text-2xl font-black sm:text-3xl">{siteConfig.closingCta.title}</h2>
          </div>
          <DynamicCta
            cta={{
              label: siteConfig.closingCta.label,
              type: "page",
              target: siteConfig.closingCta.target,
              arrow: true,
            }}
            onNavigate={onNavigate}
            className="bg-white"
          />
        </div>
      </section>
    </motion.div>
  );
}

// src/pages/Home.vue
<template>
  <div class="space-y-8">
    <!-- Introduction Section -->
    <section class="rounded-xl border border-slate-200 bg-white p-6 sm:p-8 shadow-sm">
      <p class="font-mono text-xs font-semibold uppercase tracking-wider text-blue-600 mb-2">
        Profile Brief
      </p>
      <h2 class="text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">
        {{ siteConfig.brand.name }}
      </h2>
      <p class="mt-3 max-w-2xl text-base leading-relaxed text-slate-600">
        Fokus membangun arsitektur Backend tangguh, otomatisasi infrastruktur Cloud/DevOps, dan pertahanan Cyber Security.
      </p>

      <!-- Proof Strip for HR / Recruiters -->
      <div class="mt-4 flex flex-wrap items-center gap-2 font-mono text-[11px] text-slate-600">
        <span class="inline-flex items-center gap-1 rounded bg-slate-100 px-2.5 py-1 border border-slate-200">
          <span class="h-1.5 w-1.5 rounded-full bg-blue-600"></span>
          Top 14 CTF Nasional
        </span>
        <span class="inline-flex items-center gap-1 rounded bg-slate-100 px-2.5 py-1 border border-slate-200">
          <span class="h-1.5 w-1.5 rounded-full bg-emerald-600"></span>
          15+ Verified Credentials
        </span>
        <span class="inline-flex items-center gap-1 rounded bg-slate-100 px-2.5 py-1 border border-slate-200">
          <span class="h-1.5 w-1.5 rounded-full bg-indigo-600"></span>
          Go REST API &amp; K8s Cluster
        </span>
      </div>

      <div class="mt-6 flex flex-wrap gap-2.5">
        <DynamicCta
          v-for="cta in siteConfig.homeCtas"
          :key="`${cta.type}-${cta.target || cta.linkKey}`"
          :cta="cta"
          @navigate="$emit('navigate', $event)"
        />
      </div>
    </section>

    <!-- Strengths / Core Pillars in Dashed Cards -->
    <section class="space-y-4" aria-labelledby="pillars-title">
      <div class="flex items-center justify-between">
        <h3 id="pillars-title" class="font-mono text-xs font-bold uppercase tracking-wider text-slate-500">
          Keahlian &amp; Fokus Inti
        </h3>
      </div>

      <div class="grid gap-3 sm:grid-cols-3">
        <article
          v-for="strength in strengths"
          :key="strength.title"
          class="dashed-card p-5 flex flex-col justify-between"
        >
          <div>
            <div class="flex items-center justify-between mb-3">
              <span class="font-mono text-xs font-bold text-blue-600 bg-blue-50 px-2 py-0.5 rounded border border-blue-200">
                {{ strength.number }}
              </span>
            </div>
            <h4 class="text-base font-bold text-slate-900">{{ strength.title }}</h4>
            <p class="mt-2 text-xs leading-relaxed text-slate-600">{{ strength.description }}</p>
          </div>
        </article>
      </div>

      <!-- Secondary / Exploratory Strip: Agentic AI -->
      <div class="rounded-lg border border-slate-200 bg-slate-50/70 px-4 py-3 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2.5">
        <div class="flex items-center gap-2.5">
          <span class="inline-flex items-center rounded bg-slate-200/80 px-2 py-0.5 font-mono text-[10px] font-bold text-slate-700 uppercase tracking-wide">
            Eksplorasi &amp; Tooling
          </span>
          <span class="text-xs font-bold text-slate-800">Agentic AI &amp; Autonomous Workflows</span>
        </div>
        <p class="text-[11px] text-slate-500 max-w-xl">
          Mengeksplorasi orkestrasi multi-agent dan automasi workflow cerdas sebagai pengganda efisiensi pengembangan sistem.
        </p>
      </div>
    </section>

    <!-- Notion Engineering Vault Callout Section -->
    <section class="rounded-xl border border-blue-100 bg-blue-50/50 p-6 transition-all hover:border-blue-200">
      <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div class="space-y-1">
          <div class="inline-flex items-center gap-1.5 rounded-full bg-blue-100/80 px-2.5 py-0.5 font-mono text-[10px] font-bold text-blue-800">
            <span>LIVE NOTION VAULT</span>
          </div>
          <h3 class="text-base font-bold text-slate-900">Engineering Notes &amp; Incident Playbooks</h3>
          <p class="text-xs text-slate-600 max-w-xl">
            Akses langsung dokumentasi arsitektur, catatan lab K8s, cheatsheet CTF, dan riset sistem yang diperbarui secara berkala di Notion.
          </p>
        </div>
        <a
          :href="siteConfig.links.notionNotes.href"
          target="_blank"
          rel="noopener noreferrer"
          class="clean-button-primary inline-flex items-center justify-center gap-1.5 text-xs font-semibold shrink-0 self-start sm:self-center"
        >
          <span>Buka Notion Vault</span>
          <span>↗</span>
        </a>
      </div>
    </section>

    <!-- Recent Highlights / Quick Vault & Notes Section -->
    <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
      <div class="flex items-center justify-between border-b border-slate-100 pb-4">
        <div>
          <h3 class="text-base font-bold text-slate-900">Catatan &amp; Eksplorasi Terbaru</h3>
          <p class="text-xs text-slate-500">Disinkronkan langsung dari Notion Hub Publik</p>
        </div>
        <a
          :href="siteConfig.links.notionNotes.href"
          target="_blank"
          rel="noreferrer"
          class="font-mono text-xs font-semibold text-blue-600 hover:text-blue-700 hover:underline"
        >
          Lihat Semua Catatan ↗
        </a>
      </div>

      <div class="mt-4 divide-y divide-slate-100">
        <!-- Live Notion Sync Note Item (Max 3 items with line-clamp) -->
        <a
          v-for="note in notes.slice(0, 3)"
          :key="note.id"
          :href="note.url"
          target="_blank"
          rel="noreferrer"
          class="py-3.5 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 hover:bg-slate-50/80 px-2 rounded-lg transition-colors group"
        >
          <div class="flex items-center gap-3 overflow-hidden">
            <span class="font-mono text-[10px] font-bold uppercase tracking-wide bg-blue-50 text-blue-700 border border-blue-200 px-1.5 py-0.5 rounded shrink-0">[Notion Note]</span>
            <span class="text-sm font-semibold text-slate-900 group-hover:text-blue-600 transition-colors shrink-0">
              {{ note.title }}
            </span>
            <span class="text-xs text-slate-500 line-clamp-1 truncate">— {{ note.excerpt }}</span>
          </div>
          <span class="font-mono text-xs text-slate-400 self-start sm:self-auto shrink-0">{{ note.date }} ↗</span>
        </a>

        <!-- Recent Activities -->
        <div
          v-for="item in recentActivities"
          :key="item.title"
          class="py-3.5 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 hover:bg-slate-50/80 px-2 rounded-lg transition-colors cursor-pointer"
          @click="$emit('navigate', 'projects')"
        >
          <div class="flex items-center gap-3">
            <span class="font-mono text-xs text-slate-400">[{{ item.tag }}]</span>
            <span class="text-sm font-semibold text-slate-900 hover:text-blue-600 transition-colors">
              {{ item.title }}
            </span>
          </div>
          <span class="font-mono text-xs text-slate-400 self-start sm:self-auto">{{ item.date }}</span>
        </div>
      </div>
    </section>

    <!-- Quick CTA Banner -->
    <section class="rounded-xl border border-slate-200 bg-slate-900 p-6 text-white shadow-sm flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
      <div>
        <h3 class="text-lg font-bold">{{ siteConfig.closingCta.title }}</h3>
        <p class="text-xs text-slate-400 mt-1">Terbuka untuk diskusi proyek infrastruktur, CTF, atau kolaborasi open source.</p>
      </div>
      <button
        type="button"
        @click="$emit('navigate', siteConfig.closingCta.target)"
        class="clean-button bg-white text-slate-900 border-white hover:bg-slate-100 text-xs shrink-0"
      >
        {{ siteConfig.closingCta.label }} →
      </button>
    </section>
  </div>
</template>

<script setup>
import DynamicCta from "../components/DynamicCta.vue";
import { siteConfig } from "../data/SiteConfig";
import notesData from "../data/NotesData.json";

defineEmits(["navigate"]);

const notes = notesData;

const strengths = [
  {
    number: "01",
    title: "Cloud & DevOps",
    description: "Membangun deployment dan infrastruktur yang rapi, otomatis, serta mudah dirawat.",
  },
  {
    number: "02",
    title: "Cyber Security",
    description: "Terbiasa melihat sistem dari sisi keamanan, forensik digital, dan kompetisi CTF.",
  },
  {
    number: "03",
    title: "Backend Engineering",
    description: "Mendesain arsitektur API yang tangguh, performan, dan terintegrasi database secara modular.",
  },
];

const recentActivities = [
  {
    tag: "DevOps",
    title: "Docker Image Optimization Pipeline",
    date: "2026",
  },
  {
    tag: "Security",
    title: "Digital Forensics & CTF Challenge Workflows",
    date: "2026",
  },
  {
    tag: "Tooling",
    title: "CLI Automation & CSV to JSON Parser in Go",
    date: "2025",
  },
];
</script>
