// src/components/Layout.vue
<template>
  <div class="min-h-screen bg-slate-50/60 text-slate-900 selection:bg-blue-100 selection:text-blue-900">
    <a
      href="#main-content"
      class="clean-button fixed left-4 top-4 z-50 -translate-y-24 focus:translate-y-0 shadow-sm"
    >
      Lewati ke konten
    </a>

    <div class="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
      <!-- Profile Header / Sidebar in ariaf.my.id inspired layout -->
      <header class="mb-8 rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
        <div class="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between">
          <div class="flex items-start gap-4">
            <div class="relative shrink-0">
              <img
                src="/avatar.jpg"
                :alt="siteConfig.brand.name"
                class="h-16 w-16 rounded-xl border border-slate-200 object-cover shadow-xs"
              />
              <span class="absolute -bottom-1 -right-1 flex h-3.5 w-3.5 items-center justify-center">
                <span class="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-75" />
                <span class="relative inline-flex h-3 w-3 rounded-full bg-emerald-500 border-2 border-white" />
              </span>
            </div>

            <div>
              <div class="flex items-center gap-2">
                <h1 class="text-xl font-bold tracking-tight text-slate-900">
                  {{ siteConfig.brand.name }}
                </h1>
                <span class="rounded-full bg-emerald-50 px-2 py-0.5 font-mono text-[11px] font-semibold text-emerald-700 border border-emerald-200">
                  Online
                </span>
              </div>
              <p class="text-sm font-medium text-slate-500">
                {{ siteConfig.brand.role }}
              </p>
              <div class="mt-2.5 flex items-center gap-3">
                <template v-for="linkKey in siteConfig.footerLinkKeys" :key="linkKey">
                  <a
                    v-if="getSiteLink(linkKey)"
                    :href="getSiteLink(linkKey).href"
                    target="_blank"
                    rel="noreferrer"
                    :aria-label="getSiteLink(linkKey).label"
                    class="flex h-8 w-8 items-center justify-center rounded-lg border border-slate-200 bg-slate-50 text-slate-600 hover:border-slate-400 hover:bg-slate-100 hover:text-slate-900 transition-colors"
                  >
                    <DynamicIcon :name="getSiteLink(linkKey).icon" class="text-sm" />
                  </a>
                </template>
              </div>
            </div>
          </div>

          <!-- Desktop Quick Actions -->
          <div class="flex items-center gap-2 self-start sm:self-center">
            <button
              type="button"
              @click="$emit('open-palette')"
              class="flex items-center gap-1.5 rounded-lg border border-slate-200 bg-slate-50 px-2.5 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-100 hover:text-slate-900 transition-colors"
              title="Command Palette (Cmd+K)"
            >
              <DynamicIcon name="search" class="text-xs" />
              <span>Cari</span>
              <kbd class="rounded bg-white px-1 py-0.5 text-[10px] font-mono border border-slate-200 shadow-2xs text-slate-400">⌘K</kbd>
            </button>
            <button
              type="button"
              @click="navigate('contact-me')"
              class="clean-button clean-button-primary text-xs"
            >
              Kontak
            </button>
          </div>
        </div>

        <!-- Navigation Bar (Clean Tabs) -->
        <nav class="mt-6 flex flex-wrap gap-1 border-t border-slate-100 pt-4" aria-label="Navigasi utama">
          <button
            v-for="item in siteConfig.navigation"
            :key="item.id"
            type="button"
            @click="navigate(item.id)"
            :aria-current="isNavbar === item.id ? 'page' : undefined"
            :class="[
              'rounded-lg px-3.5 py-1.5 text-xs font-semibold transition-all',
              isNavbar === item.id
                ? 'bg-slate-900 text-white'
                : 'text-slate-600 hover:bg-slate-100 hover:text-slate-900'
            ]"
          >
            {{ item.label }}
          </button>
        </nav>
      </header>

      <!-- Main Content Viewport -->
      <main id="main-content" class="min-h-[calc(100vh-320px)]">
        <slot />
      </main>

      <!-- Minimal Clean Footer -->
      <footer class="mt-12 border-t border-slate-200 pt-6 text-center text-xs text-slate-500">
        <p>
          Dibuat dengan dedikasi &amp; arsitektur minimalis oleh {{ siteConfig.brand.name }}.
        </p>
      </footer>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from "vue";
import DynamicIcon from "./DynamicIcon.vue";
import { getSiteLink, isExternalLink, siteConfig } from "../data/SiteConfig";

const props = defineProps({
  currentPage: {
    type: String,
    default: "/",
  },
});

const emit = defineEmits(["navigate"]);

const isNavbar = computed(() => props.currentPage);
const githubLink = computed(() => getSiteLink("github"));

const navigate = (pageId) => {
  emit("navigate", pageId);
  window.scrollTo({ top: 0, behavior: "smooth" });
};
</script>

// src/components/Layout.jsx
import { AiOutlineClose } from "@react-icons/all-files/ai/AiOutlineClose";
import { FiMenu } from "@react-icons/all-files/fi/FiMenu";
import { useState } from "react";
import DynamicIcon from "./DynamicIcon";
import { getSiteLink, isExternalLink, siteConfig } from "../data/SiteConfig";

export default function Layout({ children, setIsNavbar, isNavbar }) {
  const [navbarOpen, setNavbarOpen] = useState(false);
  const githubLink = getSiteLink("github");

  const navigate = (id) => {
    setIsNavbar(id);
    setNavbarOpen(false);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <div className="pixel-grid min-h-screen overflow-x-hidden">
      <a
        href="#main-content"
        className="pixel-button fixed left-4 top-4 z-50 -translate-y-24 focus:translate-y-0"
      >
        Lewati ke konten
      </a>

      <header className="sticky top-0 z-40 border-b-[3px] border-[#17213c] bg-[#fffaf0]">
        <div className="mx-auto flex min-h-[76px] max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8">
          <button
            type="button"
            className="flex min-h-[48px] items-center gap-3 text-left"
            onClick={() => navigate(siteConfig.navigation[0].id)}
            aria-label="Buka halaman utama"
          >
            <span className="grid h-11 w-11 place-items-center border-2 border-[#17213c] bg-[#ffd166] shadow-[3px_3px_0_#17213c] pixel-font text-sm">
              {siteConfig.brand.initials}
            </span>
            <span>
              <span className="pixel-font block text-[10px] sm:text-xs">{siteConfig.brand.shortName}</span>
              <span className="block text-xs font-bold text-[#5d6475] sm:text-sm">
                {siteConfig.brand.role}
              </span>
            </span>
          </button>

          <nav className="hidden items-center gap-2 md:flex" aria-label="Navigasi utama">
            {siteConfig.navigation.map((item, index) => (
              <button
                type="button"
                key={item.id}
                onClick={() => navigate(item.id)}
                aria-current={isNavbar === item.id ? "page" : undefined}
                className={`min-h-[44px] border-2 border-[#17213c] px-4 py-2 text-sm font-bold transition-colors ${
                  isNavbar === item.id
                    ? "bg-[#6c5ce7] text-white shadow-[3px_3px_0_#17213c]"
                    : "bg-[#fffaf0] hover:bg-[#ffd166]"
                }`}
              >
                <span className="mr-2 text-xs opacity-70">{String(index + 1).padStart(2, "0")}</span>
                {item.label}
              </button>
            ))}
          </nav>

          <a
            href={githubLink.href}
            target="_blank"
            rel="noreferrer"
            className="hidden min-h-[44px] items-center gap-2 border-2 border-[#17213c] bg-[#17213c] px-4 py-2 font-bold text-white transition-colors hover:bg-[#4338a8] lg:flex"
          >
            <DynamicIcon name={githubLink.icon} className="text-xl" />
            {githubLink.label}
          </a>

          <button
            type="button"
            className="grid h-12 w-12 place-items-center border-2 border-[#17213c] bg-[#ffd166] shadow-[3px_3px_0_#17213c] md:hidden"
            onClick={() => setNavbarOpen((current) => !current)}
            aria-expanded={navbarOpen}
            aria-controls="mobile-navigation"
            aria-label={navbarOpen ? "Tutup menu" : "Buka menu"}
          >
            {navbarOpen ? <AiOutlineClose className="text-2xl" /> : <FiMenu className="text-2xl" />}
          </button>
        </div>

        {navbarOpen ? (
          <nav
            id="mobile-navigation"
            className="border-t-[3px] border-[#17213c] bg-[#f3e7cd] p-4 md:hidden"
            aria-label="Navigasi mobile"
          >
            <div className="mx-auto grid max-w-7xl gap-3">
              {siteConfig.navigation.map((item, index) => (
                <button
                  type="button"
                  key={item.id}
                  onClick={() => navigate(item.id)}
                  aria-current={isNavbar === item.id ? "page" : undefined}
                  className={`min-h-[48px] border-2 border-[#17213c] px-4 text-left font-bold shadow-[3px_3px_0_#17213c] ${
                    isNavbar === item.id ? "bg-[#6c5ce7] text-white" : "bg-[#fffaf0]"
                  }`}
                >
                  {String(index + 1).padStart(2, "0")}. {item.label}
                </button>
              ))}
            </div>
          </nav>
        ) : null}
      </header>

      <main id="main-content" className="min-h-[calc(100vh-76px)]">
        {children}
      </main>

      <footer className="border-t-[3px] border-[#17213c] bg-[#17213c] text-white">
        <div className="mx-auto flex max-w-7xl flex-col gap-3 px-4 py-6 text-sm sm:px-6 md:flex-row md:items-center md:justify-between lg:px-8">
          <p className="font-semibold">Dibuat dengan rasa ingin tahu dan banyak kopi.</p>
          <div className="flex flex-wrap gap-x-5 gap-y-2">
            {siteConfig.footerLinkKeys.map((linkKey) => {
              const link = getSiteLink(linkKey);
              const className = "font-bold underline-offset-4 hover:underline";

              return isExternalLink(link.href) ? (
                <a key={linkKey} className={className} href={link.href} target="_blank" rel="noreferrer">
                  {link.label}
                </a>
              ) : (
                <a key={linkKey} className={className} href={link.href}>
                  {link.label}
                </a>
              );
            })}
          </div>
        </div>
      </footer>
    </div>
  );
}
